version: "3"

services:
     leet9-backend:
         build:
             context: .
         command: node server.js
         ports:
             - 3000:3000
         networks:
             - dev-network

networks:
    dev-network:
        driver: bridge
