version: '3.8'
services:
  leet9-backend:
    build:
      context: ./src
      target: dev
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"