name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker Hub
      env: 
       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t cicd-pipeline ./src
    
    - name: Give Docker Image tag
      run: docker latest cicd-pipeline[:latest] k190147/cicd-pipeline[:latest]
      
    - name: Push Docker Image     
      run: docker push k190147/cicd-pipeline:latest
